// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Calculate a natal chart. Returns JSON string.
Future<String> calculateNatalChart({
  required String birthDate,
  required String birthTime,
  required double latitude,
  required double longitude,
  required double timezone,
  required String houseSystem,
  required String name,
  required String location,
}) => RustLib.instance.api.crateApiAstroCalculateNatalChart(
  birthDate: birthDate,
  birthTime: birthTime,
  latitude: latitude,
  longitude: longitude,
  timezone: timezone,
  houseSystem: houseSystem,
  name: name,
  location: location,
);

/// Calculate all chart types (natal, transit, progressions, returns).
/// Input and output as JSON strings.
Future<String> calculateMulti({required String inputJson}) =>
    RustLib.instance.api.crateApiAstroCalculateMulti(inputJson: inputJson);

/// Calculate synastry between two people. Input/output as JSON strings.
Future<String> calculateSynastryChart({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiAstroCalculateSynastryChart(inputJson: inputJson);

/// Calculate progressions. Returns JSON string.
Future<String> calculateProgressions({
  required String birthDate,
  required String birthTime,
  required double latitude,
  required double longitude,
  required double timezone,
  required String houseSystem,
  required String progressionDate,
  required String method,
}) => RustLib.instance.api.crateApiAstroCalculateProgressions(
  birthDate: birthDate,
  birthTime: birthTime,
  latitude: latitude,
  longitude: longitude,
  timezone: timezone,
  houseSystem: houseSystem,
  progressionDate: progressionDate,
  method: method,
);

/// Find solar return chart for a given year. Returns JSON string.
Future<String> findSolarReturn({
  required String birthDate,
  required String birthTime,
  required double latitude,
  required double longitude,
  required double timezone,
  required String houseSystem,
  required int year,
}) => RustLib.instance.api.crateApiAstroFindSolarReturn(
  birthDate: birthDate,
  birthTime: birthTime,
  latitude: latitude,
  longitude: longitude,
  timezone: timezone,
  houseSystem: houseSystem,
  year: year,
);

/// Geocode a Chinese location by name. Returns JSON array of GeoLocation.
///
/// Accepts "省 - 市 - 区" format or direct city/district name.
/// Returns empty array for non-Chinese or unknown locations.
Future<String> geocodeChina({required String query}) =>
    RustLib.instance.api.crateApiAstroGeocodeChina(query: query);

/// Find lunar return chart closest to target_date. Returns JSON string.
Future<String> findLunarReturn({
  required String birthDate,
  required String birthTime,
  required double latitude,
  required double longitude,
  required double timezone,
  required String houseSystem,
  required String targetDate,
}) => RustLib.instance.api.crateApiAstroFindLunarReturn(
  birthDate: birthDate,
  birthTime: birthTime,
  latitude: latitude,
  longitude: longitude,
  timezone: timezone,
  houseSystem: houseSystem,
  targetDate: targetDate,
);

/// Scan daily transit events (transit planets vs natal chart). Input/output as JSON strings.
Future<String> scanTransitEventsJson({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiAstroScanTransitEventsJson(inputJson: inputJson);

/// Scan transit events over a date range. Input/output as JSON strings.
/// Input: `{ birth_date, birth_time, latitude, longitude, timezone, house_system, start_date, days }`
/// Output: JSON array of daily scan results.
Future<String> scanTransitRangeJson({required String inputJson}) => RustLib
    .instance
    .api
    .crateApiAstroScanTransitRangeJson(inputJson: inputJson);

/// Scan daily sky aspects (transit-to-transit, universal). Input/output as JSON strings.
Future<String> scanSkyAspectsJson({required String inputJson}) =>
    RustLib.instance.api.crateApiAstroScanSkyAspectsJson(inputJson: inputJson);
