// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/astro.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1807210302;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_astro',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAstroCalculateMulti({required String inputJson});

  Future<String> crateApiAstroCalculateNatalChart({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String name,
    required String location,
  });

  Future<String> crateApiAstroCalculateProgressions({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String progressionDate,
    required String method,
  });

  Future<String> crateApiAstroCalculateSynastryChart({
    required String inputJson,
  });

  Future<String> crateApiAstroFindLunarReturn({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String targetDate,
  });

  Future<String> crateApiAstroFindSolarReturn({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required int year,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAstroCalculateMulti({required String inputJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroCalculateMultiConstMeta,
        argValues: [inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroCalculateMultiConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_multi",
        argNames: ["inputJson"],
      );

  @override
  Future<String> crateApiAstroCalculateNatalChart({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String name,
    required String location,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(birthDate, serializer);
          sse_encode_String(birthTime, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          sse_encode_f_64(timezone, serializer);
          sse_encode_String(houseSystem, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(location, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroCalculateNatalChartConstMeta,
        argValues: [
          birthDate,
          birthTime,
          latitude,
          longitude,
          timezone,
          houseSystem,
          name,
          location,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroCalculateNatalChartConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_natal_chart",
        argNames: [
          "birthDate",
          "birthTime",
          "latitude",
          "longitude",
          "timezone",
          "houseSystem",
          "name",
          "location",
        ],
      );

  @override
  Future<String> crateApiAstroCalculateProgressions({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String progressionDate,
    required String method,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(birthDate, serializer);
          sse_encode_String(birthTime, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          sse_encode_f_64(timezone, serializer);
          sse_encode_String(houseSystem, serializer);
          sse_encode_String(progressionDate, serializer);
          sse_encode_String(method, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroCalculateProgressionsConstMeta,
        argValues: [
          birthDate,
          birthTime,
          latitude,
          longitude,
          timezone,
          houseSystem,
          progressionDate,
          method,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroCalculateProgressionsConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_progressions",
        argNames: [
          "birthDate",
          "birthTime",
          "latitude",
          "longitude",
          "timezone",
          "houseSystem",
          "progressionDate",
          "method",
        ],
      );

  @override
  Future<String> crateApiAstroCalculateSynastryChart({
    required String inputJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroCalculateSynastryChartConstMeta,
        argValues: [inputJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroCalculateSynastryChartConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_synastry_chart",
        argNames: ["inputJson"],
      );

  @override
  Future<String> crateApiAstroFindLunarReturn({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required String targetDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(birthDate, serializer);
          sse_encode_String(birthTime, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          sse_encode_f_64(timezone, serializer);
          sse_encode_String(houseSystem, serializer);
          sse_encode_String(targetDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroFindLunarReturnConstMeta,
        argValues: [
          birthDate,
          birthTime,
          latitude,
          longitude,
          timezone,
          houseSystem,
          targetDate,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroFindLunarReturnConstMeta =>
      const TaskConstMeta(
        debugName: "find_lunar_return",
        argNames: [
          "birthDate",
          "birthTime",
          "latitude",
          "longitude",
          "timezone",
          "houseSystem",
          "targetDate",
        ],
      );

  @override
  Future<String> crateApiAstroFindSolarReturn({
    required String birthDate,
    required String birthTime,
    required double latitude,
    required double longitude,
    required double timezone,
    required String houseSystem,
    required int year,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(birthDate, serializer);
          sse_encode_String(birthTime, serializer);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          sse_encode_f_64(timezone, serializer);
          sse_encode_String(houseSystem, serializer);
          sse_encode_i_32(year, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAstroFindSolarReturnConstMeta,
        argValues: [
          birthDate,
          birthTime,
          latitude,
          longitude,
          timezone,
          houseSystem,
          year,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAstroFindSolarReturnConstMeta =>
      const TaskConstMeta(
        debugName: "find_solar_return",
        argNames: [
          "birthDate",
          "birthTime",
          "latitude",
          "longitude",
          "timezone",
          "houseSystem",
          "year",
        ],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
